### ISSUE TITLE
纯CSS实现三角形

### ISSUE THREAD

**Issue by goldEli** [goldEli/Front-end-Knowledge-Points#16]

**Comment by goldEli** [comment]
```css
    .triangle_to_top{
      width: 0; 
      height: 0; 
      border-top: 10px solid transparent;
      border-bottom: 10px solid blue;
      border-left: 10px solid transparent;
      border-right: 10px solid transparent;
    }
    .triangle_to_left{
      width: 0; 
      height: 0; 
      border-top: 10px solid transparent;
      border-bottom: 10px solid transparent;
      border-right: 10px solid red;
    }
    .triangle_to_right{
      width: 0; 
      height: 0; 
      border-top: 10px solid transparent;
      border-bottom: 10px solid transparent;
      
      border-left: 10px solid green;
    }
    .triangle_to_bottom{
      width: 0; 
      height: 0; 
      border-top: 10px solid brown;
      border-left: 10px solid transparent;
      border-right: 10px solid transparent;
    }
```
```html
    <div class="triangle_to_top"></div>
    <div class="triangle_to_right"></div>
    <div class="triangle_to_bottom"></div>
    <div class="triangle_to_left"></div>
```
